### PR TITLE
Debug tcp scan test failures

### LINKED ISSUE #127: [bug][eldritch] allocate_unusued_ports fails when port is already in use.
**Describe the bug**
When multiple network based tests are running ports can be selected through `allocate_localhost_unused_ports` but by the time they get to `setup_test_listener` they can already have been bound. 

**To Reproduce**
```bash
while true; do cargo test -- --skip test_process_shell_current_user --nocapture; sleep 1; done
```
**Expected behavior**
Tests should pass

**Screenshots**
image

### PR DESCRIPTION
**Pull request by hulto**
#### What type of PR is this?
/kind failing-test

#### Which issue(s) this PR fixes:
Fixes #127

### CODE REVIEW

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 1]
```diff
@@ -140,8 +140,11 @@ async fn tcp_connect_scan_socket(target_host: String, target_port: i32) -> Resul
                 "Connection refused (os error 61)" if cfg!(target_os = "macos") => {
                     return Ok((target_host, target_port, "tcp".to_string(), "closed".to_string()));
                 },
+                "Connection reset by peer (os error 54)" if cfg!(target_os = "macos") => {
+                    return Ok((target_host, target_port, "tcp".to_string(), "closed".to_string()));
+                },
                 _ => {
-                    return Err(anyhow::Error::from(err));
+                    return Err(anyhow::anyhow!("Any unexpeceted error occured during the scan:\n{}", err));
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:147]: nit: Unexpected

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 2]
```diff
@@ -176,8 +179,11 @@ async fn udp_scan_socket(target_host: String, target_port: i32) -> Result<(Strin
                 "An existing connection was forcibly closed by the remote host. (os error 10054)" if cfg!(target_os = "windows") => {
                     return Ok((target_host, target_port, "udp".to_string(), "closed".to_string()));
                 },
+                "Connection reset by peer (os error 54)" if cfg!(target_os = "macos") => {
+                    return Ok((target_host, target_port, "tcp".to_string(), "closed".to_string()));
+                },
                 _ => {
-                    return Err(anyhow::Error::from(err));
+                    return Err(anyhow::anyhow!("Any unexpeceted error occured during the scan:\n{}", err));
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:186]: nit: Unexpected

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 3]
```diff
@@ -140,8 +140,11 @@ async fn tcp_connect_scan_socket(target_host: String, target_port: i32) -> Resul
                 "Connection refused (os error 61)" if cfg!(target_os = "macos") => {
                     return Ok((target_host, target_port, "tcp".to_string(), "closed".to_string()));
                 },
+                "Connection reset by peer (os error 54)" if cfg!(target_os = "macos") => {
+                    return Ok((target_host, target_port, "tcp".to_string(), "closed".to_string()));
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:144]: is it possible to make "tcp" and "closed" constants that we return?

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 4]
```diff
@@ -309,10 +315,10 @@ async fn handle_port_scan(target_cidrs: Vec<String>, ports: Vec<i32>, protocol:
             Ok(res) => {
                 result.push(res);
             },
-            Err(err) => return Err(anyhow::Error::from(err)),
+            Err(err) => return Err(anyhow::anyhow!("Async task await failed:\n{}", err)),
         };
     }
-
+    println!("Result: {:?}", result);
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:321]: Remove `println` in production code

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 5]
```diff
@@ -489,21 +439,42 @@ mod tests {
...
+        }
+    }
+
     #[tokio::test]
     async fn test_portscan_tcp() -> anyhow::Result<()> {
-        let test_ports =  allocate_localhost_unused_ports(4, "tcp".to_string()).await?;
-
+        // Allocate unused ports
+        let mut bound_listeners_vec: Vec<TcpListener> = vec![];
+        for _ in 0..(3) {
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:467]: image

Let's define this as a constant

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 6]
```diff
@@ -512,9 +483,11 @@ mod tests {
             handle_port_scan(test_cidr, test_ports.clone(), String::from("tcp"), 5)
         );
 
+        let mut listen_task_iter = listen_tasks.into_iter();
+        
         // Run both
         let (_a, _b, _c, actual_response) =
-            tokio::join!(listen_task1,listen_task2,listen_task3,send_task);
+            tokio::join!(listen_task_iter.next().unwrap(),listen_task_iter.next().unwrap(),listen_task_iter.next().unwrap(),send_task);
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:490]: `unwrap()` is a war crime 👀

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 7]
```diff
@@ -529,8 +502,7 @@ mod tests {
         let expected_response: Vec<(String, i32, String, String)>;
         expected_response = vec![(host.clone(),test_ports[0],proto.clone(),"open".to_string()),
                 (host.clone(),test_ports[1],proto.clone(),"open".to_string()),
-                (host.clone(),test_ports[2],proto.clone(),"open".to_string()),
-                (host.clone(),test_ports[3],proto.clone(),"closed".to_string())];
+                (host.clone(),test_ports[2],proto.clone(),"open".to_string())];
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:505]: Code would be more readable if we defined "open" as a constant or a variable, a lot of extra code calling `to_string()` inline makes it a bit more difficult to read this

File: implants/eldritch/src/pivot/port_scan_impl.rs [hunk 8]
```diff
@@ -615,17 +587,8 @@ mod tests {
...
-            .enable_all()
-            .build()
-            .unwrap();
-
-        let response = runtime.block_on(
-            allocate_localhost_unused_ports(4,"tcp".to_string())
-        );
 
-        let test_ports = response.unwrap();
+        let test_ports: Vec<i32> = (8000..8004).map(|x| x).collect();
```
Comment (KCarretto) [inline implants/eldritch/src/pivot/port_scan_impl.rs:591]: nit: Might be more readable to just list out the 4 values?

**Review by KCarretto — APPROVED** [review]
Please change

File: implants/eldritch/src/pivot/port_scan_impl.rs (hunk 6 above)
Comment (hulto) [reply implants/eldritch/src/pivot/port_scan_impl.rs:490]: Gonna leave this since it's running in test code.

File: implants/eldritch/src/pivot/port_scan_impl.rs (hunk 7 above)
Comment (hulto) [reply implants/eldritch/src/pivot/port_scan_impl.rs:505]: We'll still have to call `to_string()` since const can only be a &str.
Updated to consts though.

File: implants/eldritch/src/pivot/port_scan_impl.rs (hunk 8 above)
Comment (hulto) [reply implants/eldritch/src/pivot/port_scan_impl.rs:591]: I'm so cool though.
